### ISSUE TITLE
Panel issues

### ISSUE THREAD

**Issue by Disti4ct** [noxonsu/LotteryFactory#30]
After fetchilng lottery status:
* starting from width: ~1640px
![image](https://user-images.githubusercontent.com/61930014/158952326-2edcfebe-e07c-49d6-8219-a65a3972c741.png)

Also [ + / - ] buttons don't work

**Comment by shendel** [comment]
[ + / - ] Работают - это автораспределение
Если после выставления шанса на каждое совпадение - остались свободные проценты (от 100%) - то при нажатии на эту кнопку - в указаном поле бедет перерасчет
Возмет 100% - отнимет другие заполненные поля и в указанное поле установит остаток %
